"""
Builds the static HTML site into the docs/ directory.
"""

import json
import sqlite3
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, BaseLoader

from config import TOPICS
from database import get_all_studies, get_summary, get_study_count, get_all_stats, get_top_stats, get_stats

# ---------------------------------------------------------------------------
# Jinja2 templates
# ---------------------------------------------------------------------------

BASE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}Plant-Based Research Hub{% endblock %}</title>
  <link rel="stylesheet" href="{{ assets_prefix }}assets/style.css?v={{ build_ts }}" />
</head>
<body>
  <nav class="navbar">
    <div class="nav-container">
      <a class="nav-brand" href="{{ root_prefix }}index.html">🌿 Plant-Based Research Hub</a>
      <ul class="nav-links">
        <li><a href="{{ root_prefix }}index.html">Home</a></li>
        <li><a href="{{ root_prefix }}topics/index.html">Topics</a></li>
        <li><a href="{{ root_prefix }}database/index.html">Database</a></li>
        <li><a href="{{ root_prefix }}stats/index.html">Key Statistics</a></li>
        <li><a href="{{ root_prefix }}about/index.html">About</a></li>
      </ul>
    </div>
  </nav>
  <main>
    {% block content %}{% endblock %}
  </main>
  <footer>
    <div class="footer-container">
      <p>Data sourced from <a href="https://pubmed.ncbi.nlm.nih.gov/" target="_blank" rel="noopener">PubMed / NCBI</a>. Summaries generated by AI. Not medical advice.</p>
      <p>Last updated: {{ last_updated }}</p>
    </div>
  </footer>
  <script src="{{ assets_prefix }}assets/main.js?v={{ build_ts }}"></script>
  {% block extra_scripts %}{% endblock %}
</body>
</html>
"""

INDEX_TEMPLATE = """{% extends "base.html" %}
{% block title %}Plant-Based Research Hub — Evidence-Based Nutrition{% endblock %}
{% block content %}
<section class="hero">
  <div class="hero-inner">
    <h1>Plant-Based Research Hub</h1>
    <p class="hero-subtitle">An automatically updated database of peer-reviewed research on plant-based diets, sourced daily from PubMed.</p>
    <p class="hero-meta">{{ total_studies }} studies tracked across {{ topic_count }} topics &mdash; last updated {{ last_updated }}</p>
  </div>
</section>

{% if stat_of_day %}
<section class="container stat-of-day-section">
  <div class="stat-of-day-box">
    <div class="stat-of-day-label">&#8212;&#8212; Stat of the Day &#8212;&#8212;</div>
    <p class="stat-of-day-text">&#x1F4A1; &ldquo;{{ stat_of_day.stat_sentence }}&rdquo;</p>
    <div class="stat-of-day-meta">
      &mdash; {{ stat_of_day.authors or "Unknown" }}{% if stat_of_day.year %}, {{ stat_of_day.year }}{% endif %}
      &middot;
      {% if stat_of_day.quality_tier == 1 %}Meta-analysis
      {% elif stat_of_day.quality_tier == 2 %}RCT
      {% elif stat_of_day.quality_tier == 3 %}Cohort
      {% elif stat_of_day.quality_tier == 4 %}Cross-Sectional
      {% else %}Study{% endif %}
      &nbsp;
      <button class="copy-btn"
        data-copy-sentence="{{ stat_of_day.stat_sentence | e }}"
        data-copy-authors="{{ (stat_of_day.authors or '') | e }}"
        data-copy-year="{{ stat_of_day.year or '' }}"
        data-copy-study-type="{{ (stat_of_day.study_type or '') | e }}"
        data-copy-pmid="{{ stat_of_day.pmid or '' }}"
        onclick="copyStatCitation(this)">&#x1F4CB; Copy</button>
      &nbsp;
      <a href="{{ root_prefix }}stats/index.html" class="view-all-stats-link">View all stats &rarr;</a>
    </div>
  </div>
</section>
{% endif %}

<section class="topics-section container">
  <h2>Research Topics</h2>
  <div class="topic-grid">
    {% for topic in topics %}
    <div class="topic-card">
      <div class="topic-card-header">
        <h3>
          <a href="{{ root_prefix }}topics/{{ topic.key }}/index.html">{{ topic.name }}</a>
          {% if topic.not_fully_plant_based %}<span class="tag-warning">(not fully plant-based)</span>{% endif %}
        </h3>
        <span class="study-count">{{ topic.study_count }} studies</span>
      </div>
      <p class="topic-description">{{ topic.description }}</p>
      {% if topic.summary %}
      <p class="topic-consensus">{{ topic.summary[:200] }}{% if topic.summary|length > 200 %}...{% endif %}</p>
      {% else %}
      <p class="topic-consensus no-summary">Summary not yet generated.</p>
      {% endif %}
      <a class="read-more" href="{{ root_prefix }}topics/{{ topic.key }}/index.html">Read more &rarr;</a>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}
"""

TOPICS_INDEX_TEMPLATE = """{% extends "base.html" %}
{% block title %}All Topics — Plant-Based Research Hub{% endblock %}
{% block content %}
<div class="container page-container">
  <h1>Research Topics</h1>
  <p>Browse {{ topic_count }} research topics. Each page summarizes the current evidence, including consensus, conflicts, limitations, and open questions.</p>
  <div class="topic-grid">
    {% for topic in topics %}
    <div class="topic-card">
      <div class="topic-card-header">
        <h3>
          <a href="{{ root_prefix }}topics/{{ topic.key }}/index.html">{{ topic.name }}</a>
          {% if topic.not_fully_plant_based %}<span class="tag-warning">(not fully plant-based)</span>{% endif %}
        </h3>
        <span class="study-count">{{ topic.study_count }} studies</span>
      </div>
      <p class="topic-description">{{ topic.description }}</p>
      <a class="read-more" href="{{ root_prefix }}topics/{{ topic.key }}/index.html">View evidence &rarr;</a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}
"""

TOPIC_PAGE_TEMPLATE = """{% extends "base.html" %}
{% block title %}{{ topic_name }} — Plant-Based Research Hub{% endblock %}
{% block content %}
<div class="container page-container">
  <a class="back-link" href="{{ root_prefix }}index.html">&larr; Back to Home</a>

  <div class="topic-header">
    <h1>
      {{ topic_name }}
      {% if not_fully_plant_based %}<span class="tag-warning">(Mediterranean diet — not fully plant-based)</span>{% endif %}
    </h1>
    <p class="topic-description-large">{{ topic_description }}</p>
  </div>

  <div class="stats-bar">
    <span><strong>{{ study_count }}</strong> studies tracked</span>
    <span>Strongest evidence: <strong>{{ strongest_evidence }}</strong></span>
    {% if last_updated %}<span>Last updated: <strong>{{ last_updated }}</strong></span>{% endif %}
  </div>

  {% if no_rct_warning %}
  <div class="warning-box">
    <strong>Note:</strong> No randomized controlled trials or meta-analyses found for this topic. Findings are based on observational data only.
  </div>
  {% endif %}

  {% if summary %}
  <div class="summary-sections">
    <div class="collapsible-section" data-open="true">
      <button class="section-toggle">
        <span class="section-title">1. Current Consensus</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        <div class="section-body">{{ summary.current_consensus | safe }}</div>
      </div>
    </div>

    <div class="collapsible-section" data-open="true">
      <button class="section-toggle">
        <span class="section-title">2. How the Evidence Has Evolved</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        <div class="section-body">{{ summary.evidence_evolution | safe }}</div>
      </div>
    </div>

    <div class="collapsible-section" data-open="true">
      <button class="section-toggle">
        <span class="section-title">3. Where Studies Agree</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        <div class="section-body">{{ summary.agreements | safe }}</div>
      </div>
    </div>

    <div class="collapsible-section" data-open="true">
      <button class="section-toggle">
        <span class="section-title">4. Where Studies Conflict</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        <div class="section-body">{{ summary.conflicts | safe }}</div>
      </div>
    </div>

    <div class="collapsible-section" data-open="true">
      <button class="section-toggle">
        <span class="section-title">5. Limitations &amp; Controversies</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        <div class="section-body">{{ summary.limitations | safe }}</div>
      </div>
    </div>

    <div class="collapsible-section" data-open="true">
      <button class="section-toggle">
        <span class="section-title">6. What We Still Don't Know</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        <div class="section-body">{{ summary.unknowns | safe }}</div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="info-box">
    <p>No summary has been generated for this topic yet. Check back after the next daily update.</p>
  </div>
  {% endif %}

  {% if topic_stats %}
  <section class="topic-stats-section">
    <h2>Key Statistics</h2>
    {% for stat in topic_stats %}
    <div class="stat-card tier-{{ stat.quality_tier }}">
      <div class="stat-card-header">
        <span class="quality-badge tier-{{ stat.quality_tier }}">
          {% if stat.quality_tier == 1 %}Meta-analysis
          {% elif stat.quality_tier == 2 %}RCT
          {% elif stat.quality_tier == 3 %}Cohort
          {% elif stat.quality_tier == 4 %}Cross-Sectional
          {% else %}Study{% endif %}
        </span>
        {% if stat.is_contested %}<span class="contested-badge">&#9888; Conflicting evidence</span>{% endif %}
      </div>
      <p class="stat-sentence">&ldquo;{{ stat.stat_sentence }}&rdquo;</p>
      {% if stat.original_quote %}
      <div class="stat-quote-toggle">
        <button class="abstract-btn" data-target="stat-quote-{{ stat.id }}">Show original quote</button>
        <div class="abstract-content" id="stat-quote-{{ stat.id }}" style="display:none;">
          <p>{{ stat.original_quote }}</p>
        </div>
      </div>
      {% endif %}
      {% if stat.confidence_interval %}<p class="stat-ci">CI: {{ stat.confidence_interval }}</p>{% endif %}
      <p class="stat-meta">
        {{ stat.authors or "Unknown" }}{% if stat.year %}, {{ stat.year }}{% endif %}
        &middot;
        {% if stat.quality_tier == 1 %}meta-analysis
        {% elif stat.quality_tier == 2 %}RCT
        {% elif stat.quality_tier == 3 %}cohort
        {% elif stat.quality_tier == 4 %}cross-sectional
        {% else %}study{% endif %}
        &middot; {{ topic_name }}
      </p>
      <button class="copy-btn"
        data-copy-sentence="{{ stat.stat_sentence | e }}"
        data-copy-authors="{{ (stat.authors or '') | e }}"
        data-copy-year="{{ stat.year or '' }}"
        data-copy-study-type="{{ (stat.study_type or '') | e }}"
        data-copy-pmid="{{ stat.pmid or '' }}"
        onclick="copyStatCitation(this)">&#x1F4CB; Copy citation</button>
    </div>
    {% endfor %}
  </section>
  {% endif %}

  <section class="studies-section">
    <div class="section-header-row">
      <h2>Studies ({{ study_count }} total)</h2>
      <div class="sort-control">
        <label for="topic-sort">Sort by:</label>
        <select id="topic-sort">
          <option value="year-desc">Most Recent</option>
          <option value="year-asc">Oldest First</option>
          <option value="tier-asc">Highest Quality</option>
          <option value="n-desc">Largest Study</option>
        </select>
      </div>
    </div>
    <div id="topic-studies-list">
    {% for study in studies %}
    <div class="study-card tier-{{ study.quality_tier }}"
         data-year="{{ study.pub_year or 0 }}"
         data-tier="{{ study.quality_tier or 5 }}"
         data-n="{{ study.sample_size or 0 }}">
      <div class="study-card-header">
        <span class="quality-badge tier-{{ study.quality_tier }}">
          {% if study.quality_tier == 1 %}Meta-Analysis / Systematic Review
          {% elif study.quality_tier == 2 %}RCT
          {% elif study.quality_tier == 3 %}Cohort / Observational
          {% elif study.quality_tier == 4 %}Cross-Sectional
          {% else %}Case / Opinion
          {% endif %}
        </span>
        <span class="study-year">{{ study.pub_year or "N/A" }}</span>
        {% if study.sample_size %}<span class="sample-size">n={{ study.sample_size }}</span>{% endif %}
      </div>
      <h3 class="study-title">
        <a href="{{ study.pubmed_url }}" target="_blank" rel="noopener">{{ study.title }}</a>
      </h3>
      <p class="study-meta">
        {{ study.authors or "Authors unknown" }}
        {% if study.journal %} &mdash; <em>{{ study.journal }}</em>{% endif %}
        {% if study.pub_year %}, {{ study.pub_year }}{% endif %}
        &mdash; <a href="{{ study.pubmed_url }}" target="_blank" rel="noopener">PMID {{ study.pmid }}</a>
      </p>
      {% if study.abstract %}
      <div class="abstract-toggle">
        <button class="abstract-btn" data-target="abstract-{{ study.pmid }}">Show Abstract</button>
        <div class="abstract-content" id="abstract-{{ study.pmid }}" style="display:none;">
          <p>{{ study.abstract }}</p>
        </div>
      </div>
      {% endif %}
    </div>
    {% endfor %}
    </div>{# end topic-studies-list #}
  </section>
</div>
{% endblock %}
"""

DATABASE_TEMPLATE = """{% extends "base.html" %}
{% block title %}Study Database — Plant-Based Research Hub{% endblock %}
{% block extra_scripts %}
<script src="https://unpkg.com/lunr/lunr.js"></script>
{% endblock %}
{% block content %}
<div class="container page-container">
  <h1>Study Database</h1>
  <p>Browse all {{ total_studies }} studies in the database. Use the search and filters to narrow results.</p>

  <div class="search-bar-wrapper">
    <input type="search" id="db-search" class="search-bar" placeholder="Search titles, abstracts, authors..." />
  </div>

  <div class="filter-panel">
    <div class="filter-group">
      <label for="filter-topic">Topic</label>
      <select id="filter-topic" multiple size="4">
        {% for key, config in topics.items() %}
        <option value="{{ key }}">{{ config.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="filter-group">
      <label for="filter-type">Study Type</label>
      <select id="filter-type">
        <option value="">All types</option>
        <option value="meta-analysis">Meta-Analysis / Systematic Review</option>
        <option value="RCT">RCT</option>
        <option value="cohort">Cohort / Observational</option>
        <option value="cross-sectional">Cross-Sectional</option>
        <option value="case/opinion">Case / Opinion</option>
        <option value="review">Review</option>
      </select>
    </div>
    <div class="filter-group">
      <label>Year Range</label>
      <div class="year-range">
        <input type="number" id="filter-year-min" placeholder="From" min="1990" max="2100" />
        <span>–</span>
        <input type="number" id="filter-year-max" placeholder="To" min="1990" max="2100" />
      </div>
    </div>
    <div class="filter-group">
      <label for="filter-tier">Quality Tier</label>
      <select id="filter-tier">
        <option value="">All tiers</option>
        <option value="1">Tier 1 — Meta-Analysis</option>
        <option value="2">Tier 2 — RCT</option>
        <option value="3">Tier 3 — Cohort</option>
        <option value="4">Tier 4 — Cross-Sectional</option>
        <option value="5">Tier 5 — Case / Opinion</option>
      </select>
    </div>
    <div class="filter-group filter-actions">
      <button id="clear-filters" class="btn-secondary">Clear Filters</button>
    </div>
    <div class="filter-group">
      <label for="db-sort">Sort by</label>
      <select id="db-sort">
        <option value="year-desc">Most Recent</option>
        <option value="year-asc">Oldest First</option>
        <option value="tier-asc">Highest Quality</option>
        <option value="n-desc">Largest Study</option>
      </select>
    </div>
  </div>

  <p class="results-count" id="results-count">Showing {{ total_studies }} of {{ total_studies }} studies</p>

  <div class="table-wrapper">
    <table class="study-table" id="study-table">
      <thead>
        <tr>
          <th data-sort="pmid" class="sortable">PMID</th>
          <th data-sort="title" class="sortable">Title</th>
          <th data-sort="year" class="sortable">Year</th>
          <th data-sort="type" class="sortable">Type</th>
          <th data-sort="tier" class="sortable">Quality</th>
          <th data-sort="topics" class="sortable">Topics</th>
          <th data-sort="n" class="sortable">n=</th>
          <th>Link</th>
        </tr>
      </thead>
      <tbody id="study-table-body">
        {% for study in studies %}
        <tr
          data-pmid="{{ study.pmid }}"
          data-year="{{ study.pub_year or '' }}"
          data-type="{{ study.study_type or '' }}"
          data-tier="{{ study.quality_tier or '' }}"
          data-topics="{{ study.topics | join(',') }}"
          data-n="{{ study.sample_size or '' }}"
          data-title="{{ study.title | lower }}"
          data-abstract="{{ (study.abstract or '')[:300] | lower }}"
          data-authors="{{ (study.authors or '') | lower }}"
        >
          <td>{{ study.pmid }}</td>
          <td class="title-cell" title="{{ study.title }}">{{ study.title[:80] }}{% if study.title|length > 80 %}...{% endif %}</td>
          <td>{{ study.pub_year or "N/A" }}</td>
          <td>
            <span class="quality-badge tier-{{ study.quality_tier }}">{{ study.study_type or "unknown" }}</span>
          </td>
          <td>{{ study.quality_tier or "?" }}</td>
          <td class="topics-cell">
            {% for t in study.topics %}
            <span class="topic-tag">{{ topics.get(t, {}).get('name', t) }}</span>
            {% endfor %}
          </td>
          <td>{{ study.sample_size or "" }}</td>
          <td><a href="{{ study.pubmed_url }}" target="_blank" rel="noopener">PubMed</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
  // Embed search index data
  window.SEARCH_INDEX_URL = "{{ root_prefix }}search-index.json";
</script>
{% endblock %}
"""

ABOUT_TEMPLATE = """{% extends "base.html" %}
{% block title %}About — Plant-Based Research Hub{% endblock %}
{% block content %}
<div class="container page-container">
  <h1>About This Project</h1>

  <section class="about-section">
    <h2>Methodology</h2>
    <p>This site automatically retrieves peer-reviewed studies from <a href="https://pubmed.ncbi.nlm.nih.gov/" target="_blank" rel="noopener">PubMed</a> using the NCBI E-utilities API. Searches are run daily via GitHub Actions. Studies are classified by study type and quality tier using PubMed publication type metadata.</p>
    <p>Narrative summaries are generated by a large language model (Llama 3.3 70B via Groq) instructed to cite sources, use direct quotes, and distinguish evidence quality. Summaries are regenerated when new studies are added.</p>
    <p><strong>This site does not provide medical advice.</strong> All content is for informational purposes. Consult a qualified healthcare professional before making dietary changes.</p>
  </section>

  <section class="about-section">
    <h2>Evidence Hierarchy</h2>
    <table class="evidence-table">
      <thead>
        <tr>
          <th>Tier</th>
          <th>Study Type</th>
          <th>Description</th>
          <th>Confidence</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><span class="quality-badge tier-1">1</span></td>
          <td>Meta-Analysis / Systematic Review</td>
          <td>Pooled analysis of multiple studies with rigorous inclusion criteria. Highest evidence quality.</td>
          <td>Highest</td>
        </tr>
        <tr>
          <td><span class="quality-badge tier-2">2</span></td>
          <td>Randomized Controlled Trial (RCT)</td>
          <td>Participants randomly assigned to intervention or control. Can establish causation.</td>
          <td>High</td>
        </tr>
        <tr>
          <td><span class="quality-badge tier-3">3</span></td>
          <td>Cohort / Observational Study</td>
          <td>Follows groups over time, observing outcomes. Can establish association, not causation.</td>
          <td>Moderate</td>
        </tr>
        <tr>
          <td><span class="quality-badge tier-4">4</span></td>
          <td>Cross-Sectional Study</td>
          <td>Snapshot data at a single point in time. Can show association only.</td>
          <td>Low–Moderate</td>
        </tr>
        <tr>
          <td><span class="quality-badge tier-5">5</span></td>
          <td>Case Report / Editorial / Opinion</td>
          <td>Single case or expert opinion. Not generalizable.</td>
          <td>Low</td>
        </tr>
      </tbody>
    </table>
  </section>

  <section class="about-section">
    <h2>Glossary</h2>
    <dl class="glossary">
      <dt>Healthy User Bias</dt>
      <dd>A confounding factor where people who adopt a particular diet (e.g., plant-based) are also more likely to engage in other health-promoting behaviors (exercise, not smoking), making it difficult to isolate the dietary effect.</dd>

      <dt>Surrogate Marker</dt>
      <dd>A measurable biological indicator (e.g., LDL cholesterol, BMI, blood glucose) used as a substitute for a clinically meaningful endpoint (e.g., heart attack, death). Changes in surrogate markers do not always predict changes in hard endpoints.</dd>

      <dt>Confounding Variable</dt>
      <dd>A variable that is correlated with both the exposure (diet) and the outcome (health metric), potentially distorting the apparent relationship between them.</dd>

      <dt>Self-Reported Data</dt>
      <dd>Dietary information collected via questionnaires or food frequency questionnaires (FFQs) completed by participants. Subject to recall bias and social desirability bias.</dd>

      <dt>Meta-Analysis</dt>
      <dd>A statistical technique that combines results from multiple independent studies on the same question to produce a pooled estimate with greater statistical power.</dd>

      <dt>Randomized Controlled Trial (RCT)</dt>
      <dd>An experimental study where participants are randomly assigned to an intervention group or a control group, allowing researchers to infer causation.</dd>

      <dt>Cohort Study</dt>
      <dd>An observational study that follows a group of people over time, comparing those exposed to a factor (e.g., a plant-based diet) with those not exposed, to see who develops a given outcome.</dd>

      <dt>Cross-Sectional Study</dt>
      <dd>A study that examines a population at a single point in time, measuring both exposure and outcome simultaneously. Cannot establish temporal sequence or causation.</dd>
    </dl>
  </section>

  <section class="about-section">
    <h2>Data Sources</h2>
    <ul>
      <li><a href="https://pubmed.ncbi.nlm.nih.gov/" target="_blank" rel="noopener">PubMed / NCBI E-utilities</a> — primary source for study metadata and abstracts</li>
      <li><a href="https://groq.com/" target="_blank" rel="noopener">Groq API</a> (Llama 3.3 70B) — narrative summary generation</li>
    </ul>
  </section>

  <section class="about-section">
    <h2>Update Frequency</h2>
    <p>The database is updated every day at 06:00 UTC via a GitHub Actions workflow. New studies published in the past year are fetched on each run. Summaries are regenerated for topics that have received new studies. All summaries are regenerated every Sunday.</p>
    <p>You can also trigger a manual update from the GitHub repository's Actions tab.</p>
  </section>
</div>
{% endblock %}
"""


STATS_PAGE_TEMPLATE = """{% extends "base.html" %}
{% block title %}Key Statistics — Plant-Based Research Hub{% endblock %}
{% block content %}
<div class="container page-container">
  <div class="stats-page-hero">
    <h1>Key Statistics</h1>
    <p class="hero-subtitle-inline">Specific quantitative findings extracted from peer-reviewed studies. Click any stat to copy a shareable citation.</p>
  </div>

  <div class="filter-panel stats-filter-panel">
    <div class="filter-group">
      <label for="stats-filter-topic">Topic</label>
      <select id="stats-filter-topic">
        <option value="">All Topics</option>
        {% for key, config in topics.items() %}
        <option value="{{ key }}">{{ config.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="filter-group">
      <label for="stats-filter-diet">Diet Type</label>
      <select id="stats-filter-diet">
        <option value="">All</option>
        <option value="vegan">Vegan</option>
        <option value="vegetarian">Vegetarian</option>
        <option value="plant-based">Plant-based</option>
        <option value="meat-free">Meat-free</option>
        <option value="other">Other</option>
      </select>
    </div>
    <div class="filter-group">
      <label for="stats-filter-direction">Direction</label>
      <select id="stats-filter-direction">
        <option value="">All</option>
        <option value="reduction">Reductions only</option>
        <option value="increase">Increases only</option>
        <option value="null">Null findings</option>
      </select>
    </div>
    <div class="filter-group">
      <label for="stats-filter-quality">Study Quality</label>
      <select id="stats-filter-quality">
        <option value="">All</option>
        <option value="highonly">Meta-analyses &amp; RCTs only</option>
      </select>
    </div>
    <div class="filter-group filter-actions">
      <button id="stats-clear-filters" class="btn-secondary">Clear Filters</button>
    </div>
    <div class="filter-group">
      <label for="stats-sort">Sort by</label>
      <select id="stats-sort">
        <option value="year-desc">Most Recent</option>
        <option value="year-asc">Oldest First</option>
        <option value="tier-asc">Highest Quality</option>
        <option value="n-desc">Largest Study</option>
        <option value="magnitude-desc">Largest Effect</option>
      </select>
    </div>
  </div>

  <p class="results-count" id="stats-results-count">Showing {{ non_null_stats|length }} of {{ total_stats_count }} statistics</p>

  <section class="stats-list-section" id="stats-key-findings">
    <h2>Key Findings</h2>
    {% if non_null_stats %}
    {% for stat in non_null_stats %}
    <div class="stat-card tier-{{ stat.quality_tier }}"
         data-topic="{{ stat.topic }}"
         data-diet="{{ stat.diet_type }}"
         data-direction="{{ stat.direction }}"
         data-tier="{{ stat.quality_tier }}"
         data-year="{{ stat.year or 0 }}"
         data-magnitude="{{ stat.magnitude | replace('%','') | replace(' ','') if stat.magnitude else '0' }}">
      <div class="stat-card-header">
        <span class="quality-badge tier-{{ stat.quality_tier }}">
          {% if stat.quality_tier == 1 %}Meta-analysis
          {% elif stat.quality_tier == 2 %}RCT
          {% elif stat.quality_tier == 3 %}Cohort
          {% elif stat.quality_tier == 4 %}Cross-Sectional
          {% else %}Study{% endif %}
        </span>
        {% if stat.is_contested %}<span class="contested-badge">&#9888; Conflicting evidence</span>{% endif %}
      </div>
      <p class="stat-sentence">&ldquo;{{ stat.stat_sentence }}&rdquo;</p>
      {% if stat.original_quote %}
      <div class="stat-quote-toggle">
        <button class="abstract-btn" data-target="stat-quote-{{ stat.id }}">Show original quote</button>
        <div class="abstract-content" id="stat-quote-{{ stat.id }}" style="display:none;">
          <p>{{ stat.original_quote }}</p>
        </div>
      </div>
      {% endif %}
      {% if stat.confidence_interval %}<p class="stat-ci">CI: {{ stat.confidence_interval }}</p>{% endif %}
      <p class="stat-meta">
        {{ stat.authors or "Unknown" }}{% if stat.year %}, {{ stat.year }}{% endif %}
        &middot;
        {% if stat.quality_tier == 1 %}meta-analysis
        {% elif stat.quality_tier == 2 %}RCT
        {% elif stat.quality_tier == 3 %}cohort
        {% elif stat.quality_tier == 4 %}cross-sectional
        {% else %}study{% endif %}
        &middot; {{ topics.get(stat.topic, {}).get('name', stat.topic) }}
      </p>
      <button class="copy-btn"
        data-copy-sentence="{{ stat.stat_sentence | e }}"
        data-copy-authors="{{ (stat.authors or '') | e }}"
        data-copy-year="{{ stat.year or '' }}"
        data-copy-study-type="{{ (stat.study_type or '') | e }}"
        data-copy-pmid="{{ stat.pmid or '' }}"
        onclick="copyStatCitation(this)">&#x1F4CB; Copy citation</button>
    </div>
    {% endfor %}
    {% else %}
    <p class="no-stats-msg">No statistics available yet. Run the pipeline with a Groq API key to extract statistics.</p>
    {% endif %}
  </section>

  {% if null_stats %}
  <section class="stats-list-section" id="stats-null-findings">
    <div class="collapsible-section" data-open="false">
      <button class="section-toggle">
        <span class="section-title">Null Findings ({{ null_stats|length }})</span>
        <span class="toggle-icon">&#9660;</span>
      </button>
      <div class="section-content">
        {% for stat in null_stats %}
        <div class="stat-card tier-{{ stat.quality_tier }}"
             data-topic="{{ stat.topic }}"
             data-diet="{{ stat.diet_type }}"
             data-direction="{{ stat.direction }}"
             data-tier="{{ stat.quality_tier }}">
          <div class="stat-card-header">
            <span class="quality-badge tier-{{ stat.quality_tier }}">
              {% if stat.quality_tier == 1 %}Meta-analysis
              {% elif stat.quality_tier == 2 %}RCT
              {% elif stat.quality_tier == 3 %}Cohort
              {% elif stat.quality_tier == 4 %}Cross-Sectional
              {% else %}Study{% endif %}
            </span>
            <span class="null-finding-badge">Null finding</span>
          </div>
          <p class="stat-sentence">&ldquo;{{ stat.stat_sentence }}&rdquo;</p>
          {% if stat.original_quote %}
          <div class="stat-quote-toggle">
            <button class="abstract-btn" data-target="stat-quote-{{ stat.id }}">Show original quote</button>
            <div class="abstract-content" id="stat-quote-{{ stat.id }}" style="display:none;">
              <p>{{ stat.original_quote }}</p>
            </div>
          </div>
          {% endif %}
          {% if stat.confidence_interval %}<p class="stat-ci">CI: {{ stat.confidence_interval }}</p>{% endif %}
          <p class="stat-meta">
            {{ stat.authors or "Unknown" }}{% if stat.year %}, {{ stat.year }}{% endif %}
            &middot;
            {% if stat.quality_tier == 1 %}meta-analysis
            {% elif stat.quality_tier == 2 %}RCT
            {% elif stat.quality_tier == 3 %}cohort
            {% elif stat.quality_tier == 4 %}cross-sectional
            {% else %}study{% endif %}
            &middot; {{ topics.get(stat.topic, {}).get('name', stat.topic) }}
          </p>
          <button class="copy-btn"
            data-copy-sentence="{{ stat.stat_sentence | e }}"
            data-copy-authors="{{ (stat.authors or '') | e }}"
            data-copy-year="{{ stat.year or '' }}"
            data-copy-study-type="{{ (stat.study_type or '') | e }}"
            data-copy-pmid="{{ stat.pmid or '' }}"
            onclick="copyStatCitation(this)">&#x1F4CB; Copy citation</button>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  {% endif %}

</div>
{% endblock %}
"""


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

def _make_env() -> Environment:
    """Create a Jinja2 environment with our inline templates."""
    env = Environment(loader=BaseLoader())
    now = datetime.utcnow()
    env.globals["last_updated"] = now.strftime("%Y-%m-%d %H:%M UTC")
    env.globals["build_ts"] = now.strftime("%Y%m%d%H%M")

    # Register templates
    template_map = {
        "base.html": BASE_HTML,
        "index.html": INDEX_TEMPLATE,
        "topics_index.html": TOPICS_INDEX_TEMPLATE,
        "topic_page.html": TOPIC_PAGE_TEMPLATE,
        "database.html": DATABASE_TEMPLATE,
        "about.html": ABOUT_TEMPLATE,
        "stats.html": STATS_PAGE_TEMPLATE,
    }

    # Patch the loader to serve our inline templates
    class InlineLoader(BaseLoader):
        def get_source(self, environment, template):
            if template in template_map:
                source = template_map[template]
                return source, template, lambda: True
            raise Exception(f"Template not found: {template}")

    env.loader = InlineLoader()
    return env


def _determine_strongest_evidence(studies: list[dict]) -> str:
    if not studies:
        return "none"
    tiers = [s.get("quality_tier") for s in studies if s.get("quality_tier")]
    if not tiers:
        return "observational"
    best = min(tiers)
    mapping = {
        1: "meta-analyses / systematic reviews",
        2: "randomized controlled trials",
        3: "cohort / observational studies",
        4: "cross-sectional studies",
        5: "case reports / opinions",
    }
    return mapping.get(best, "observational")


def _has_rct_or_meta(studies: list[dict]) -> bool:
    return any(s.get("quality_tier", 5) <= 2 for s in studies)


def build_static_site(conn: sqlite3.Connection, docs_path: Path) -> None:
    """Generate all static HTML files into docs_path."""
    docs_path = Path(docs_path)
    docs_path.mkdir(parents=True, exist_ok=True)

    env = _make_env()
    last_updated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Ensure .nojekyll exists
    (docs_path / ".nojekyll").touch()

    all_studies = get_all_studies(conn)
    total_studies = len(all_studies)

    # Collect topic data
    topic_list = []
    for topic_key in sorted(TOPICS.keys()):
        cfg = TOPICS[topic_key]
        count = get_study_count(conn, topic_key)
        summary_row = get_summary(conn, topic_key)
        consensus_text = summary_row["current_consensus"] if summary_row else None
        topic_list.append({
            "key": topic_key,
            "name": cfg["name"],
            "description": cfg["description"],
            "not_fully_plant_based": cfg.get("not_fully_plant_based", False),
            "study_count": count,
            "summary": consensus_text,
        })

    # Compute Stat of the Day
    top_stats = get_top_stats(conn, n=20)
    stat_of_day = None
    if top_stats:
        today_date = datetime.utcnow().date()
        stat_of_day = top_stats[hash(str(today_date)) % len(top_stats)]

    # ------------------------------------------------------------------
    # 1. Homepage: docs/index.html
    # ------------------------------------------------------------------
    tmpl = env.get_template("index.html")
    html = tmpl.render(
        topics=topic_list,
        topic_count=len(TOPICS),
        total_studies=total_studies,
        last_updated=last_updated,
        stat_of_day=stat_of_day,
        root_prefix="",
        assets_prefix="",
    )
    (docs_path / "index.html").write_text(html, encoding="utf-8")
    print(f"  Built: docs/index.html")

    # ------------------------------------------------------------------
    # 2. Topics index: docs/topics/index.html
    # ------------------------------------------------------------------
    topics_dir = docs_path / "topics"
    topics_dir.mkdir(exist_ok=True)

    tmpl = env.get_template("topics_index.html")
    html = tmpl.render(
        topics=topic_list,
        topic_count=len(TOPICS),
        last_updated=last_updated,
        root_prefix="../",
        assets_prefix="../",
    )
    (topics_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"  Built: docs/topics/index.html")

    # ------------------------------------------------------------------
    # 3. Individual topic pages: docs/topics/{key}/index.html
    # ------------------------------------------------------------------
    tmpl = env.get_template("topic_page.html")
    for topic_key, cfg in TOPICS.items():
        from database import get_studies_for_topic
        topic_studies = get_studies_for_topic(conn, topic_key, min_quality_tier=5)
        # Sort by pub_year DESC
        topic_studies.sort(key=lambda s: s.get("pub_year") or 0, reverse=True)

        summary_row = get_summary(conn, topic_key)
        strongest = _determine_strongest_evidence(topic_studies)
        show_warning = not _has_rct_or_meta(topic_studies)

        topic_dir = topics_dir / topic_key
        topic_dir.mkdir(exist_ok=True)

        last_upd = summary_row["last_updated"][:10] if summary_row and summary_row.get("last_updated") else None

        # Get non-null stats for this topic
        topic_stats = get_stats(conn, topic=topic_key, direction=None)
        topic_stats_non_null = [s for s in topic_stats if s.get("direction") != "null"]

        html = tmpl.render(
            topic_name=cfg["name"],
            topic_description=cfg["description"],
            not_fully_plant_based=cfg.get("not_fully_plant_based", False),
            study_count=len(topic_studies),
            strongest_evidence=strongest,
            last_updated=last_upd,
            no_rct_warning=show_warning,
            summary=summary_row,
            studies=topic_studies,
            topic_stats=topic_stats_non_null,
            root_prefix="../../",
            assets_prefix="../../",
        )
        (topic_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"  Built: docs/topics/{{topic}}/index.html ({len(TOPICS)} pages)")

    # ------------------------------------------------------------------
    # 4. Database page: docs/database/index.html
    # ------------------------------------------------------------------
    db_dir = docs_path / "database"
    db_dir.mkdir(exist_ok=True)

    tmpl = env.get_template("database.html")
    html = tmpl.render(
        total_studies=total_studies,
        studies=all_studies,
        topics=TOPICS,
        last_updated=last_updated,
        root_prefix="../",
        assets_prefix="../",
    )
    (db_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"  Built: docs/database/index.html")

    # ------------------------------------------------------------------
    # 5. Stats page: docs/stats/index.html
    # ------------------------------------------------------------------
    stats_dir = docs_path / "stats"
    stats_dir.mkdir(exist_ok=True)

    all_stats = get_all_stats(conn)
    non_null_stats = [s for s in all_stats if s.get("direction") != "null"]
    null_stats = [s for s in all_stats if s.get("direction") == "null"]
    total_stats_count = len(all_stats)

    tmpl = env.get_template("stats.html")
    html = tmpl.render(
        non_null_stats=non_null_stats,
        null_stats=null_stats,
        total_stats_count=total_stats_count,
        topics=TOPICS,
        last_updated=last_updated,
        root_prefix="../",
        assets_prefix="../",
    )
    (stats_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"  Built: docs/stats/index.html ({total_stats_count} stats)")

    # ------------------------------------------------------------------
    # 6. About page: docs/about/index.html
    # ------------------------------------------------------------------
    about_dir = docs_path / "about"
    about_dir.mkdir(exist_ok=True)

    tmpl = env.get_template("about.html")
    html = tmpl.render(
        last_updated=last_updated,
        root_prefix="../",
        assets_prefix="../",
    )
    (about_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"  Built: docs/about/index.html")

    # ------------------------------------------------------------------
    # 8. Search index: docs/search-index.json
    # ------------------------------------------------------------------
    search_index = []
    for study in all_studies:
        abstract = study.get("abstract") or ""
        search_index.append({
            "id": study["pmid"],
            "title": study.get("title", ""),
            "abstract_excerpt": abstract[:200],
            "topics": study.get("topics", []),
            "year": study.get("pub_year"),
            "study_type": study.get("study_type", ""),
        })
    (docs_path / "search-index.json").write_text(
        json.dumps(search_index, ensure_ascii=False, indent=None),
        encoding="utf-8",
    )
    print(f"  Built: docs/search-index.json ({len(search_index)} entries)")

    # ------------------------------------------------------------------
    # 9. Assets (CSS + JS)
    # ------------------------------------------------------------------
    assets_dir = docs_path / "assets"
    assets_dir.mkdir(exist_ok=True)

    print(f"  Site build complete. Total studies: {total_studies}")

if __name__ == "__main__":
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent))
    from database import get_connection, init_db
    PROJECT_ROOT = Path(__file__).parent.parent
    conn = get_connection(str(PROJECT_ROOT / "data" / "studies.db"))
    init_db(conn)
    build_static_site(conn, PROJECT_ROOT / "docs")
    conn.close()
